seeder:
  image: my-seeder
  mongoNewUser: user1
  mongoNewPassword: password1

mongo:
  db: rizz
  host: mongo
  port: 27017
  start_username: admin
  start_password: password

postgres:
  host: postgres
  port: 5432
  start_username: admin
  start_password: password
  db: rizz
