apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: my-client
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.client.clientPort }}
          env:
            - name: VITE_API_HOST
              value: {{ .Values.client.apiHost | quote }}
            - name: VITE_API_PORT
              value: {{ .Values.client.apiPort | quote }}
            - name: VITE_CLIENT_PORT
              value: {{ .Values.client.clientPort | quote }}
