apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.client.clientPort }}
      targetPort: {{ .Values.client.clientPort }}
  selector:
    app: client
