apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: NodePort
  ports:
    - port: {{ .Values.mongo.port }}
      targetPort: {{ .Values.mongo.port }}
      nodePort: {{ .Values.mongo.nodePort }}
  selector:
    app: mongo
