version: '3'
name: online-rizz-shop
services:
  service-mongo:
    build: 
      context: ./docker/mongodb
    image: my-mongo:lastest
    pull_policy: never
    ports:
      - "27018:27017"
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MON_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MON_PASSWORD}
    volumes:
      - mongodata:/data/db
  
  service-postgres:
    build: 
      context: ./docker/postgres
    image: my-postgres:lastest
    pull_policy: never
    ports:
      - "5433:5432"
    networks:
      - backend
    environment:
      POSTGRES_USER: ${POST_USERNAME}
      POSTGRES_PASSWORD: ${POST_PASSWORD}
    volumes:
      - postgresdata:/var/lib/postgresql/data
  
  service-rabbitmq:
    build: 
      context: ./docker/rabbitmq
    image: my-rabbitmq:lastest
    pull_policy: never
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - backend
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

volumes:
  mongodata:
    driver: local
  postgresdata:
    driver: local
  rabbitmqdata:
    driver: local

networks:
  backend:
