
FROM node:24-alpine

# set working directory
WORKDIR /

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application
COPY . .

# Build TypeScript to JavaScript
RUN npm run build

# expose port
# EXPOSE 8080

CMD ["node", "dist/app.js"]