apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-svc
  namespace: ors
  labels:
    app: api-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-svc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api-svc
    spec:
      containers:
        - name: api-svc
          envFrom:
          - secretRef:
              name: test-secret
          image: my-api
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:3003/health
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
          ports:
            - containerPort: 3003
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: api-pvc
      restartPolicy: Always
      volumes:
        - name: api-pvc
          persistentVolumeClaim:
            claimName: api-pvc
