apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-svc
  namespace: ors
  labels:
    app: api-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-svc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api-svc
    spec:
      initContainers:
        - name: wait-for-mongo
          image: busybox:1.28
          command:
            [
              "sh",
              "-c",
              "until nslookup mongo-svc.ors.svc.cluster.local; do echo waiting for mongo; sleep 2; done;",
            ]
        - name: wait-for-postgres
          image: busybox:1.28
          command:
            [
              "sh",
              "-c",
              "until nslookup postgres-svc.ors.svc.cluster.local; do echo waiting for postgres; sleep 2; done;",
            ]
        - name: wait-for-seeder
          image: busybox:1.28
          command: ["sh", "-c", "sleep 15"]
      containers:
        - name: api-svc
          image: my-api
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: app-env-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 20
            periodSeconds: 30
            failureThreshold: 5
          ports:
            - containerPort: 3003
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: api-pvc
      restartPolicy: Always
      volumes:
        - name: api-pvc
          persistentVolumeClaim:
            claimName: api-pvc
