apiVersion: v1
kind: Service
metadata:
  name: client-svc
  namespace: ors
  labels:
    app: client-svc
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 80
  selector:
    app: client-svc
