apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.node-selector: ors-data
    kompose.service.type: nodeport
  name: mongo-svc
  namespace: ors
  labels:
    app: mongo-svc
spec:
  ports:
    - name: "27018"
      port: 27018
      targetPort: 27017
  selector:
    app: mongo-svc
  type: NodePort
