apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.node-selector: ors-data
    kompose.service.type: nodeport
  name: mongo-svc
  namespace: ors
  labels:
    app: mongo-svc
spec:
  type: NodePort
  selector:
    app: mongo-svc
  ports:
    - port: 27018 # service port
      targetPort: 27017 # container port
      nodePort: 30019 # static port on host

