apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.node-selector: ors-data
    kompose.service.type: nodeport
  name: postgres-svc
  namespace: ors
  labels:
    app: postgres-svc
spec:
  ports:
    - port: 5433
      targetPort: 5432
  selector:
    app: postgres-svc
  type: NodePort
