apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-svc
  namespace: ors
  labels:
    app: postgres-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-svc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-svc
    spec:
      containers:
        - name: postgres-svc
          envFrom:
            - secretRef:
                name: app-env-secret
          image: my-postgres
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - pg_isready -U admin
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-pvc
      restartPolicy: Always
      volumes:
        - name: postgres-pvc
          persistentVolumeClaim:
            claimName: postgres-pvc
