apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: queuehandler
  name: queuehandler
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
