apiVersion: apps/v1
kind: Deployment
metadata:
  name: queueHandler-svc
  namespace: ors
  labels:
    app: queueHandler-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queueHandler-svc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: queueHandler-svc
    spec:
      containers:
        - env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: app-env-secret
                key: POSTGRES_DB
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: app-env-secret
                key: POSTGRES_HOST
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-env-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: app-env-secret
                key: POSTGRES_PORT
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: app-env-secret
                key: POSTGRES_USERNAME
          - name: RABBITMQ_HOST
            valueFrom:
              secretKeyRef:
                name: app-env-secret
                key: RABBITMQ_HOST
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-env-secret
                key: RABBITMQ_PASSWORD
          - name: RABBITMQ_PORT
            valueFrom:
              secretKeyRef:
                name: app-env-secret
                key: RABBITMQ_PORT
          - name: RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: app-env-secret
                key: RABBITMQ_USERNAME
          image: my-queuehandler
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:3003/health
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: queueHandler-svc
          volumeMounts:
            - mountPath: /data
              name: queueHandler-pvc
      restartPolicy: Always
      volumes:
        - name: queueHandler-pvc
          persistentVolumeClaim:
            claimName: queueHandler-pvc
