apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
  namespace: ors
  labels:
    app: rabbitmq-svc
spec:
  ports:
    - name: "5673"
      port: 5673
      targetPort: 5672
    - name: "15673"
      port: 15673
      targetPort: 15672
  selector:
    app: rabbitmq-svc
  type: NodePort
