apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-svc
  namespace: ors
  labels:
    app: rabbitmq-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-svc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rabbitmq-svc
    spec:
      containers:
        - env:
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: app-env-secret
                key: RABBITMQ_DEFAULT_PASS
          - name: RABBITMQ_DEFAULT_USER
            valueFrom:
              secretKeyRef:
                name: app-env-secret
                key: RABBITMQ_DEFAULT_USER
          image: my-rabbitmq
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - check_running
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: service-rabbitmq
          ports:
            - containerPort: 5672
              protocol: TCP
            - containerPort: 15672
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-pvc
      restartPolicy: Always
      volumes:
        - name: rabbitmq-pvc
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
