apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: service-ms-queuehandler
  name: service-ms-queuehandler
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service-ms-queuehandler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: service-ms-queuehandler
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-env-secret
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: app-env-secret
                  key: POSTGRES_HOST
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-env-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: app-env-secret
                  key: POSTGRES_PORT
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-env-secret
                  key: POSTGRES_USERNAME
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: app-env-secret
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-env-secret
                  key: RABBITMQ_PASSWORD
            - name: RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: app-env-secret
                  key: RABBITMQ_PORT
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-env-secret
                  key: RABBITMQ_USERNAME
          image: my-queuehandler
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:3003/health
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: service-ms-queuehandler
          volumeMounts:
            - mountPath: /data
              name: queuehandler
      restartPolicy: Always
      volumes:
        - name: queuehandler
          persistentVolumeClaim:
            claimName: queuehandler
