apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: service-client
  name: service-client
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 80
  selector:
    io.kompose.service: service-client
