apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.node-selector: ors-data
    kompose.service.type: nodeport
  labels:
    io.kompose.service: service-rabbitmq
  name: service-rabbitmq
spec:
  ports:
    - name: "5673"
      port: 5673
      targetPort: 5672
    - name: "15673"
      port: 15673
      targetPort: 15672
  selector:
    io.kompose.service: service-rabbitmq
  type: NodePort
