apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: service-client
  name: service-client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service-client
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: service-client
    spec:
      containers:
        - env:
            - name: VITE_API_HOST
              valueFrom:
                secretKeyRef:
                  name: app-env-secret
                  key: VITE_API_HOST
            - name: VITE_API_PORT
              valueFrom:
                secretKeyRef:
                  name: app-env-secret
                  key: VITE_API_PORT
          image: ghcr.io/alexander-ziegler-simonsen/my-client:latest
          name: service-client
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: client-data
      restartPolicy: Always
      volumes:
        - name: client-data
          persistentVolumeClaim:
            claimName: client-data
