apiVersion: v2
name: online-rizz-shop
description: Full stack app with API, DBs, Queue and client
version: 0.1.0

dependencies:
  - name: postgres
    version: 0.1.0
    repository: file://charts/postgres
  - name: mongo
    version: 0.1.0
    repository: file://charts/mongo
  - name: rabbitmq
    version: 0.1.0
    repository: file://charts/rabbitmq
  # - name: seeder
  #   version: 0.1.0
  #   repository: file://charts/seeder
  - name: api
    version: 0.1.0
    repository: file://charts/api
  - name: queuehandler
    version: 0.1.0
    repository: file://charts/queuehandler
  # - name: client
  #   version: 0.1.0
  #   repository: file://charts/client

