apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: NodePort
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.amqpPort }}
      targetPort: {{ .Values.rabbitmq.amqpPort }}
      nodePort: {{ .Values.rabbitmq.nodePortAMQP }}
    - name: management
      port: {{ .Values.rabbitmq.uiPort }}
      targetPort: {{ .Values.rabbitmq.uiPort }}
      nodePort: {{ .Values.rabbitmq.nodePortUI }}
  selector:
    app: rabbitmq
